name: Run Rakuten API Daily

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - name: 7回ループ実行
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_ACCESS_KEY: ${{ secrets.RAKUTEN_ACCESS_KEY }}
        run: |
          for area in fukuoka seibu kitakyusyu chikuzen kurume buzen chikugo
          do
            echo "Running $area"
            AREA=$area python main.py
          done

      - name: CSV保存
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "add csv" || echo "No changes"
          git push
